# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: EL BLOG DE ADRI :D
email: adrianlopezlab@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Esto es un sitio de prueba para la asignatura de Implatacion de Aplicaciones Web (IAW)
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: adrilopz_
github_username:  adrianlopezib

# Build settings
markdown: kramdown
